# Generated by Django 4.0.4 on 2022-05-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_backofficelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visits', models.IntegerField(default=0)),
                ('totals', models.IntegerField(default=0)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
